name: setup-node
description: "Setup Node.js - Cache dependencies - Install dependencies"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.5.0

    - name: Cache dependencies
      id: cache_dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          website/.next/cache
        key: nextjs-${{ hashFiles('website/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.css', '**/*.scss') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          nextjs-${{ hashFiles('website/package-lock.json') }}-

    - name: Install dependencies
      shell: bash
      working-directory: website
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci
